---
title: Hierarchical Linear Modeling
subtitle: 'BER 664' 
authors: [JoonHo Lee]
event: 
event_url:
location: 
abstract: 
summary: 'A graduate-level course on data analysis using regression and multilevel/hierarchical models' 

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
date: "2020-08-19T09:00:00Z"
date_end: "2020-12-15T10:30:00Z"
all_day: true

tags:
  - course
  - multilevel modeling

lastmod: "2020-08-19T10:30:00Z"
featured: yes
image:
  caption: '[Photo by Gabriel Sollmann on Unsplash](https://unsplash.com/photos/Y7d265_7i08)'
  focal_point: ''
  preview_only: true
projects: [course]

links:
- icon: images
  icon_pack: fas
  name: slides
  url: https://arm.rbind.io/slides/xaringan.html#1
---

## Course description 

Assuming  that  you  are  already  familiar  with  linear  and  logistic  regression,  hierarchical or multilevel versions of these models will be introduced.  Hierarchical models are used when  the  units  of  observation  (for  example  students)  are  grouped  within  clusters  (for  example  schools). In such clustered data,  observations for the same cluster (e.g., school) cannot be assumed to be  mutually  independent  for  given covariate  values  as  required  for  conventional  linear  and  logistic  regression.    To  allow  for  the  fact  that  responses  within  the  same  cluster  tend  to  be  more  similar  to  each other than to responses from other clusters, hierarchical models include cluster-specific random effects.    Such  models  are  also  known  as  multilevel  models,  (generalized)  linear  mixed  models,  random  coefficient  models,  and  variance  components  models.  Longitudinal  or  repeated  measures  data can also be thought of as clustered data with measurement occasions clustered within subjects. Hierarchical models for longitudinal data are also known as growth curve models. Such models will be compared with other approaches to longitudinal data analysis.

The focus of the course will be on understanding statistical models and their assumptions, as well as practical aspects of developing and estimating models to address research questions and interpreting the  findings.  Examples  will  be  mostly  from  education and  the  social  and  behavioral sciences.  


## Lecture notes

- Variance-components model
